---
- name: create webroot folder
  file: >
    path={{ item.document_root }}
    state=directory
    owner={{ item.document_root_owner|default(vhosts_document_root_owner) }}
    group={{ item.document_root_group|default(vhosts_document_root_group) }}
    mode={{ item.document_root_mode|default(vhosts_document_root_mode) }}
  with_items: vhosts

- name: config virtual host
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item.server_name}}.conf backup=yes
  with_items: vhosts
  register: vhost_changed

- name: enable virtual host
  command: a2ensite {{ item.server_name }}.conf creates=/etc/apache2/sites-enabled/{{ item.server_name }}.conf
  with_items: vhosts
  register: vhost_enabled

- name: check for syntax errors in vhost conf
  command: apache2ctl configtest
  when: vhost_changed.changed or vhost_enabled.changed

- name: reload apache webserver
  service: name=apache2 state=reloaded
  when: vhost_changed.changed or vhost_enabled.changed
